version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: docker/deploy/Dockerfile
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - 3000:3000

  mysql:
    image: mysql:5.7
    restart: unless-stopped
    container_name: guestslist
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_HOST=${DB_HOST}
      - MYSQL_PORT=${DB_PORT}
    ports:
      - 3306:3306
    volumes:
      - "./docker/mysql/dump.sql:/docker-entrypoint-initdb.d/dump.sql"
